### PR TITLE
ci: release please

### PR DESCRIPTION
**Pull request by jthegedus**
- [x] add `release-please-action` with `node` configuration
- [x] extract linting workflows into their own parallel jobs to tighten feedback loop
- [x] update `package.json` version number to align with existing GitHub release
- [x] update `nodejs` in `.tool-versions`
- [x] track `yarn` version in `.tool-versions`
- [x] add `semantic-pr` workflow

### CODE REVIEW

**Comment by m4rii0** [comment]
Hello @jthegedus, are there any plans to release a new version?

We would like to get rid of the warnings about node 12 deprecation and still pointing to the `v1` tag :)

**Comment by jthegedus** [comment]
Yes, this closed PR is evidence I am actively working on this. Plan is to merge a bunch of code from my fork, release a version and test.

**Comment by jthegedus** [comment]
https://github.com/asdf-vm/actions/releases/tag/v2.0.0

Please test and report issues!

**Comment by m4rii0** [comment]
> [`v2.0.0` (release)](https://github.com/asdf-vm/actions/releases/tag/v2.0.0)
> 
> Currently only supports full semver version:
> 
> ```
> uses: asdf-vm/actions/install@v2.0.0
> ```
> 
> Please test and report issues!

For sure! Thank you!

**Pull request closed without merging**
