### PR TITLE
feat: Update actions to use node16

### LINKED ISSUE #484: Upgrade to Node.js 16
This repository uses Node.js 12 actions, which are deprecated. GitHub Actions recently began adding the following annotation warning all users of asdf-vm/actions:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: asdf-vm/actions

### PR DESCRIPTION
**Pull request by jimmidyson**
See
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
for more details.- feat: Update actions to use node16

Fixes #484.

### CODE REVIEW

**Comment by jschiefner** [comment]
@jimmidyson could you attempt to re-run the latest build on actions? it looks like the runner could temporarily not reach github. If this fixes the build maybe this PR can be merged released.

**Comment by jimmidyson** [comment]
I don't have any way to re-run the actions I'm afraid - would need a maintainer to do so I guess.

**Comment by jschiefner** [comment]
Thank you! Maybe @jthegedus can help us out here? 👀

**Comment by jthegedus** [comment]
Hey crew, I am looking into this now. Apologies for the delay, though the changes here were small, the diff was large and so kept getting pushed back on my todo list.

I will try and resolve this CI issue and merge.

I realise this repo has been neglected, I intend to take ownership of this within the core team and get some of these other feature requests open as well as modernize the repo itself.

**Review by jthegedus — APPROVED** [review]
Alrighty, this looks good to me.

As far as releasing this specific change goes, I want to re-jig the GitHub Releases to follow the automation we have in our other repos, so until a tagged version becomes available I will ask you all to use the commit reference style:

```
steps:
  - name: asdf_install
    uses: asdf-vm/actions/install@6844d09
	# Reference a specific commit (most strict)
```

Where the SHA is the commit from `master` after the merge.

NOTE: an update to the min version of Node is considered a breaking API change to the Action, so this will release under tag `2.x`

**Comment by jimmidyson** [comment]
Interesting that the git URL didn't work, thanks for fixing it and getting this merged!

**Comment by jthegedus** [comment]
https://github.com/asdf-vm/actions/releases/tag/v2.0.0

Please test and report issues!

**Pull request merged**
